### ISSUE TITLE
Inconsistent back buttons for brew methods

### ISSUE THREAD

**Issue by Iikeli** [NiftyTreeStudios/Bean-Juice#112]
The brew methods have inconsistent values for the navigation back button.

Current behavior:
* V60 has "Brewing methods"
* Everything else has "Back"

Expected: 
The text should be same for everything, preferably "Brewing methods".

**Comment by kvaidya** [comment]
I think this is being done by SwiftUI because it needs to make sure that in the collapsed navigation bar state there needs to be enough space to show the centered title and the back button title. So it shows  "Brewing methods" for the smaller titles. 

Maybe the back button title can be completely removed to make it consistent? Just show the left chevron.

**Comment by Iikeli** [comment]
Good catch @kvaidya !
Definitely sounds like removing the back title is the way to go then.
